services:
  db:
    image: postgres:16-alpine
    container_name: budjetame-db
    environment:
      POSTGRES_USER: budjetame
      POSTGRES_PASSWORD: budjetame
      POSTGRES_DB: budjetame
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
