#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
TOTAL_MINUTES=38

banner "Oracle Cloud Always Free — deploy Budjetame"

# ── Deploy-specific helpers (authoring section) ───────────────────────────
KEY_PATH="${BUDJETAME_SSH_KEY:-$HOME/.ssh/budjetame_oracle}"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="$HOME/.venvs/oci"
OCI_PY="$VENV_DIR/bin/python $REPO/scripts/oci_api.py"

# gen_secret — a random hex string; openssl first, /dev/urandom fallback.
gen_secret() {
  openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 64
}

# run_oci — run an oci_api.py command; on failure show the API error and stop.
run_oci() {
  local out
  if ! out=$("$@" 2>&1); then
    warn "OCI call failed:"; say "$out"; exit 1
  fi
  printf '%s' "$out"
}

for need in ssh-keygen openssl uv; do
  if ! command -v "$need" >/dev/null 2>&1; then
    warn "$need not found — install it first (Termux: pkg install openssh openssl-tool; uv: curl -LsSf https://astral.sh/uv/install.sh | sh)"
    exit 1
  fi
done

if [[ ! -x "$VENV_DIR/bin/python" ]]; then
  say "Setting up the pure-Python OCI client (uv + rsa)…"
  uv venv --python 3 "$VENV_DIR" >/dev/null
  uv pip install --python "$VENV_DIR" rsa >/dev/null
fi

# ── Stage 1: SSH keypair ───────────────────────────────────────────────────
stage "SSH keypair" 2
say "The wizard needs a keypair so it can drive the VM from this machine."
if [[ -f "$KEY_PATH" ]]; then
  say "Key already exists — reusing: $KEY_PATH"
else
  say "Generating a new ed25519 keypair…"
  mkdir -p "$(dirname "$KEY_PATH")"
  ssh-keygen -t ed25519 -f "$KEY_PATH" -N "" -C "budjetame-oracle" >/dev/null
fi
say "Your PUBLIC key (paste it into the Oracle console in stage 3):"
cat "$KEY_PATH.pub"
pause "Copy the public key above, then press Enter."

# ── Stage 2: Oracle signup ──────────────────────────────────────────────────
stage "Oracle Cloud signup" 10
say "This is the only stage that takes a while: account + card verification."
say "Use your HOME region — Always Free capacity for the Ampere shape lives there."
open_url "https://signup.cloud.oracle.com"
step "Fill in the form, then verify the card (an authorization hold, never charged)."
step "When asked, pick your home region and finish the wizard."
step "Keep the Oracle account email + password handy — you need them next."
note "Card declined or account not approved is common; retry or use a different card."
pause "Done signing up? Press Enter."

# ── Stage 3: OCI API key + connection test ─────────────────────────────────
stage "OCI API key + connection test" 8
say "The wizard drives Oracle through its REST API with a pure-Python client"
say "(the official oci-cli cannot install on Termux). You upload one API key."
mkdir -p "$HOME/.oci"
KEY_FILE="$HOME/.oci/budjetame_api_key.pem"
CONF_FILE="$HOME/.oci/config"
if [[ ! -f "$KEY_FILE" ]]; then
  openssl genrsa -out "$KEY_FILE" 2048 >/dev/null 2>&1
  chmod 600 "$KEY_FILE"
fi
FP=$(openssl rsa -in "$KEY_FILE" -pubout -outform DER 2>/dev/null | openssl md5 -c | sed 's/.*= //')
if [[ -f "$CONF_FILE" ]] && grep -q "^fingerprint=$FP" "$CONF_FILE"; then
  say "API config already set up — reusing it."
else
  say "Upload this PUBLIC key to your Oracle user, then paste two OCIDs:"
  open_url "https://cloud.oracle.com"
  step "Sign in, then: top-right profile → Tenancy → copy the Tenancy OCID."
  step "Identity & Security → Users → your username → copy the User OCID."
  step "Same page → API Keys → Add API Key → paste the public key below:"
  openssl rsa -in "$KEY_FILE" -pubout 2>/dev/null
  say "The console shows a fingerprint after uploading — it must match: $FP"
  ask TENANCY_OCID "Paste the Tenancy OCID:"
  ask USER_OCID "Paste the User OCID:"
  ask REGION "Your home region (shown on the Tenancy page, e.g. eu-frankfurt-1):"
  cat > "$CONF_FILE" <<EOF
[DEFAULT]
user=$USER_OCID
tenancy=$TENANCY_OCID
fingerprint=$FP
key_file=$KEY_FILE
region=$REGION
EOF
  say "API config written to ~/.oci/config."
fi
say "Testing the connection…"
if OUT=$($OCI_PY ad-list 2>&1); then
  say "Connected — availability domain: $OUT"
else
  warn "Connection failed:"; say "$OUT"
  warn "Check the OCIDs and fingerprint, then re-run the wizard."
  exit 1
fi

# ── Stage 4: network (automatic) ────────────────────────────────────────────
stage "Network (automatic)" 2
say "Creating the VCN, internet gateway, route table, security list and subnet via the OCI API…"
VCN=$(run_oci $OCI_PY vcn-create)
say "VCN created."
IGW=$(run_oci $OCI_PY igw-create "$VCN")
say "Internet gateway created."
RT=$(run_oci $OCI_PY rt-create "$VCN" "$IGW")
say "Route table (0.0.0.0/0 → gateway) created."
SL=$(run_oci $OCI_PY sl-create "$VCN")
say "Security list (SSH + HTTP ingress) created."
SUBNET=$(run_oci $OCI_PY subnet-create "$VCN" "$RT" "$SL")
say "Subnet created."

# ── Stage 5: launch the VM (automatic) ──────────────────────────────────────
stage "Launch the VM (automatic)" 5
say "Finding the Ubuntu 24.04 ARM image and launching the free Ampere A1 instance (4 OCPU / 24 GB)…"
IMAGE=$(run_oci $OCI_PY image-list)
AD=$(run_oci $OCI_PY ad-list)
INSTANCE=$(run_oci $OCI_PY instance-launch "$SUBNET" "$AD" "$IMAGE" "$KEY_PATH.pub")
say "Instance launched — waiting for it to boot (a few minutes, progress below)."
note "Out of capacity? The API error will say so — retry later or check you are in your home region."
if ! $OCI_PY instance-wait "$INSTANCE"; then
  warn "Instance never reached RUNNING — check the console for errors, then re-run."
  exit 1
fi
VM_IP=$(run_oci $OCI_PY instance-public-ip "$INSTANCE")
write_env VM_IP "$VM_IP"
say "Instance is RUNNING at $VM_IP"

# ── Stage 5: first boot + Docker ────────────────────────────────────────────
stage "First boot + Docker install" 8
say "The instance needs 1–3 minutes to boot for the first time. Waiting…"
for _ in $(seq 1 16); do
  if ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=accept-new -i "$KEY_PATH" "ubuntu@$VM_IP" true 2>/dev/null; then
    break
  fi
  sleep 15
  warn "still waiting for SSH… (instance booting?)"
done
if ! ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=accept-new -i "$KEY_PATH" "ubuntu@$VM_IP" true 2>/dev/null; then
  warn "VM not reachable at $VM_IP — check it is Running and the IP is right, then re-run the wizard."
  exit 1
fi
say "Connected. Installing Docker (takes a minute)…"
ssh -i "$KEY_PATH" "ubuntu@$VM_IP" "curl -fsSL https://get.docker.com | sudo sh && sudo usermod -aG docker ubuntu"
say "Docker installed."

# ── Stage 6: secrets → .env ──────────────────────────────────────────────────
stage "Secrets → .env" 3
say "The wizard generates the two random secrets; you only provide your login."
POSTGRES_PASSWORD=$(_existing POSTGRES_PASSWORD || true)
[[ -n "$POSTGRES_PASSWORD" ]] || POSTGRES_PASSWORD=$(gen_secret)
BUDJETAME_JWT_SECRET=$(_existing BUDJETAME_JWT_SECRET || true)
[[ -n "$BUDJETAME_JWT_SECRET" ]] || BUDJETAME_JWT_SECRET=$(gen_secret)
ask BUDJETAME_SEED_ACCOUNT_EMAIL "Seed account email (your Budjetame login):"
ask_secret BUDJETAME_SEED_ACCOUNT_PASSWORD "Seed account password (your Budjetame login):"
warn "The Account is seeded ONCE, at first boot, from these values — check before deploying."
write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
write_env BUDJETAME_JWT_SECRET "$BUDJETAME_JWT_SECRET"
write_env BUDJETAME_SEED_ACCOUNT_EMAIL "$BUDJETAME_SEED_ACCOUNT_EMAIL"
write_env BUDJETAME_SEED_ACCOUNT_PASSWORD "$BUDJETAME_SEED_ACCOUNT_PASSWORD"

# ── Stage 7: deploy ──────────────────────────────────────────────────────────
stage "Deploy" 6
say "Shipping the repo to the VM as a git bundle (no credentials on the box)."
BUNDLE_DIR=$(mktemp -d)
git bundle create "$BUNDLE_DIR/budjetame.bundle" --all >/dev/null
scp -i "$KEY_PATH" "$BUNDLE_DIR/budjetame.bundle" "ubuntu@$VM_IP":~/budjetame.bundle
rm -rf "$BUNDLE_DIR"
ssh -i "$KEY_PATH" "ubuntu@$VM_IP" "git clone ~/budjetame.bundle budjetame-ai 2>/dev/null || (cd budjetame-ai && git pull)"
scp -i "$KEY_PATH" .env "ubuntu@$VM_IP":~/budjetame-ai/.env
say "Building images and starting the stack (2–4 min on 4 ARM cores)…"
ssh -i "$KEY_PATH" "ubuntu@$VM_IP" "cd ~/budjetame-ai && docker compose -f compose.prod.yaml up -d --build"
say "Waiting for the backend to come up…"
for _ in $(seq 1 24); do
  if ssh -i "$KEY_PATH" "ubuntu@$VM_IP" "curl -fsS http://localhost/api/health" 2>/dev/null | grep -q '"ok"'; then
    break
  fi
  sleep 5
  warn "backend not healthy yet…"
done
say "Budjetame is live at:  http://$VM_IP"
say "Log in with your seed email + password. (Plain HTTP for now — see docs/deploy-oracle.md for TLS.)"
note "Still stuck? ssh -i $KEY_PATH ubuntu@$VM_IP 'cd budjetame-ai && docker compose -f compose.prod.yaml logs -f'"

finish
